version: "3.7"
services:
  express:
    container_name: express
    build: ./backend
    ports:
      - "3333:3333"
    volumes:
      - "./backend:/backend"
    restart: always
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: front
    driver: "bridge"
  backend:
    name: back
    driver: "bridge"
